### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kotto5** [kotto5/clean_42#2]
## 掃除のデータ管理する

- [ ] http request を受け取るだけの、simple なHttp server を立てる
- [ ] 特定のエンドポイントでdb に接続し、data を入れる
- [ ] data の型を決める (cardId, stickId, timestamp)

## 掃除のデータが更新があれば、discordに通知する

- [ ] discord channel の webhookのURL を調べる
- [ ] api serverから(暫定) データ登録時に、webhook url を用いて、message を送信する
